name: "Hello world ingress3"
description: "My first real add-on!"
version: "1.22.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
# webui: http://[HOST]:[PORT:2839]/dashboard
ingress: true
# ingress_port: 8000
# ingress_entry: html/index.html
# host_network: true
# ports:
#   8000/tcp: 8000
#stage: stable, experimental or deprecated
#advanced: Set this to true to require the user to have enabled "Advanced" mode for it to show. -> AKO stage NIJE stable
#OPCIJE ZA POSTAVLJANJE ADD-ON U LIJEVI PANEL
# panel_icon
# panel_title
# panel_admin
#OPIS MOGUCNOSTI ADD-ONA
#services:
#ingress OPCIJE?
